// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Watcher struct {
	ID          uuid.UUID
	UserEmail   string
	Origin      string
	Destination string
	CreatedAt   pgtype.Timestamp
}
