// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: watchers.sql

package database

import (
	"context"
)

const createWatcher = `-- name: CreateWatcher :one
INSERT INTO watchers (user_email, origin, destination)
VALUES ($1, $2, $3)
RETURNING id, user_email, origin, destination, created_at
`

type CreateWatcherParams struct {
	UserEmail   string
	Origin      string
	Destination string
}

func (q *Queries) CreateWatcher(ctx context.Context, arg CreateWatcherParams) (Watcher, error) {
	row := q.db.QueryRow(ctx, createWatcher, arg.UserEmail, arg.Origin, arg.Destination)
	var i Watcher
	err := row.Scan(
		&i.ID,
		&i.UserEmail,
		&i.Origin,
		&i.Destination,
		&i.CreatedAt,
	)
	return i, err
}

const findMatches = `-- name: FindMatches :many
SELECT id, user_email, origin, destination, created_at FROM watchers 
WHERE origin = $1 
AND destination = $2
`

type FindMatchesParams struct {
	Origin      string
	Destination string
}

func (q *Queries) FindMatches(ctx context.Context, arg FindMatchesParams) ([]Watcher, error) {
	rows, err := q.db.Query(ctx, findMatches, arg.Origin, arg.Destination)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Watcher
	for rows.Next() {
		var i Watcher
		if err := rows.Scan(
			&i.ID,
			&i.UserEmail,
			&i.Origin,
			&i.Destination,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
