// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Trip struct {
	ID            uuid.UUID
	Origin        string
	Destination   string
	DriverID      uuid.UUID
	PriceThb      int32
	Status        string
	DepartureTime pgtype.Timestamp
	CreatedAt     pgtype.Timestamp
	UpdatedAt     pgtype.Timestamp
}
