// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: trips.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTrip = `-- name: CreateTrip :one
INSERT INTO trips (origin, destination, driver_id, price_thb, departure_time)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, origin, destination, driver_id, price_thb, status, departure_time, created_at, updated_at
`

type CreateTripParams struct {
	Origin        string
	Destination   string
	DriverID      uuid.UUID
	PriceThb      int32
	DepartureTime pgtype.Timestamp
}

func (q *Queries) CreateTrip(ctx context.Context, arg CreateTripParams) (Trip, error) {
	row := q.db.QueryRow(ctx, createTrip,
		arg.Origin,
		arg.Destination,
		arg.DriverID,
		arg.PriceThb,
		arg.DepartureTime,
	)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.Origin,
		&i.Destination,
		&i.DriverID,
		&i.PriceThb,
		&i.Status,
		&i.DepartureTime,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTripById = `-- name: GetTripById :one
SELECT id, origin, destination, driver_id, price_thb, status, departure_time, created_at, updated_at FROM trips
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTripById(ctx context.Context, id uuid.UUID) (Trip, error) {
	row := q.db.QueryRow(ctx, getTripById, id)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.Origin,
		&i.Destination,
		&i.DriverID,
		&i.PriceThb,
		&i.Status,
		&i.DepartureTime,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTrips = `-- name: ListTrips :many
SELECT id, origin, destination, driver_id, price_thb, status, departure_time, created_at, updated_at FROM trips
ORDER BY created_at DESC
`

func (q *Queries) ListTrips(ctx context.Context) ([]Trip, error) {
	rows, err := q.db.Query(ctx, listTrips)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Trip
	for rows.Next() {
		var i Trip
		if err := rows.Scan(
			&i.ID,
			&i.Origin,
			&i.Destination,
			&i.DriverID,
			&i.PriceThb,
			&i.Status,
			&i.DepartureTime,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchTrips = `-- name: SearchTrips :many
SELECT id, origin, destination, driver_id, price_thb, status, departure_time, created_at, updated_at FROM trips
WHERE origin = $1 
AND destination = $2 
AND status = 'OPEN'
ORDER BY price_thb ASC
`

type SearchTripsParams struct {
	Origin      string
	Destination string
}

func (q *Queries) SearchTrips(ctx context.Context, arg SearchTripsParams) ([]Trip, error) {
	rows, err := q.db.Query(ctx, searchTrips, arg.Origin, arg.Destination)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Trip
	for rows.Next() {
		var i Trip
		if err := rows.Scan(
			&i.ID,
			&i.Origin,
			&i.Destination,
			&i.DriverID,
			&i.PriceThb,
			&i.Status,
			&i.DepartureTime,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTripStatus = `-- name: UpdateTripStatus :exec
UPDATE trips
SET status = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateTripStatusParams struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) UpdateTripStatus(ctx context.Context, arg UpdateTripStatusParams) error {
	_, err := q.db.Exec(ctx, updateTripStatus, arg.ID, arg.Status)
	return err
}
